version: '3.0'

services:
  mc:
    image: "mymc:plugins"
    environment:
      EULA: "true"
      TYPE: PAPER
      #MEMORY: 512M
      MEMORY: 1G
      VERSION: 1.12.2
      # needed for Paper versions before 1.14
      CONSOLE: "false"
    restart: always
    ports:
      - 25565:25565
    volumes:
      - mc-paper:/data

  autoheal:
    image: "willfarrell/autoheal"
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

        # this is deprecated
        #  mc-checker:
        #    image: "mchecker:latest"
        #    restart: always
        #    depends_on:
        #      - mc
        #    #sleep while main server starts
        #    command: /bin/sh -c "sleep 300"
        #    healthcheck:
        #      test: ["CMD","python3","./mchecker.py","mc_main"]
        #      interval: "60s"
        #      #start_period: "120s"
        #      timeout: "60s"
        #      retries: 3

volumes:
  mc-paper:

